import { StyleSheet } from 'react-native';
import Colors from '../../constants/colors';

const styles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  header: {
    marginTop: 30,
    marginBottom: 40,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerSubContainer: {
    flexDirection: 'row',
  },
  Welcome: {
    fontSize: 36,
    fontFamily: 'Poppins-Regular',
  },
  Student: {
    marginLeft: 10,
    fontWeight: 'bold',
    color: Colors.button,
    fontSize: 36,
    fontFamily: 'Poppins-Regular',
  },
  hSubContainer: {
    flexDirection: 'row',
    maxWidth: '100%',
    flexWrap: 'wrap',
  },
  hsubTitle: {
    marginBottom: -6,
    marginTop: -3,
    fontSize: 27,
    fontFamily: 'Poppins-Regular',
  },
  hsubTitleMid: {
    marginTop: -3,
    marginLeft: 9,
    marginRight: 4,
    fontSize: 27,
    fontFamily: 'Poppins-SemiBold',
  },
  hsubTitle2: {
    marginRight: 15,
    marginBottom: -6,
    marginTop: -3,
    fontSize: 27,
    fontFamily: 'Poppins-Regular',
  },
  modesContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  mode: {
    padding: 20,
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 15,
    shadowColor: '#618bffff',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 7,
  },
  modeIcon: {
    width: '36%',
    padding: 15,
    borderRadius: '50%',
    backgroundColor: Colors.button,
    marginBottom: 12,
  },
  modeTitle: {
    fontSize: 13,
    color: Colors.text,
    fontFamily: 'Poppins-SemiBold',
  },
  modeDescription: {
    fontFamily: 'Poppins',
    fontSize: 13,
    marginBottom: 5,
    color: Colors.text,
  },
  button: {
    backgroundColor: Colors.button,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 11,
    fontFamily: 'Poppins-SemiBold',
    textTransform: 'none',
  },
  recentSessionsContainer: {
    padding: 16,
    borderRadius: 10,
    marginTop: 15,
    width: '100%',
    backgroundColor: '#ffffff',
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 7,
  },
  rscTitleText: {
    color: Colors.button,
    fontWeight: 700,
    fontSize: 15,
  },
  rsCard: {
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.recentSessionCard,
  },
  rsCardSub: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rscIcon: {
    width: 50,
    padding: 13,
    borderRadius: '50%',
    backgroundColor: Colors.button,
  },
  rsDetails: {
    marginLeft: 10,
  },
  rsDetailsTitle: {
    fontWeight: 700,
    fontSize: 15,
  },
  rsDetailsDate: {
    fontSize: 12.5,
  },
  homeButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: Colors.button,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    zIndex: 100,
  },
  homeButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
});

export default styles;
